/* Copyright (C) 2015-2024 Espressif Systems (Shanghai) PTE LTD */
/* SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0 */

syntax = "proto3";

/* Enums similar to ESP IDF */
enum Ctrl_VendorIEType {
	Beacon = 0;
	Probe_req = 1;
	Probe_resp = 2;
	Assoc_req = 3;
	Assoc_resp = 4;
}

enum Ctrl_VendorIEID {
	ID_0 = 0;
	ID_1 = 1;
}

enum Ctrl_WifiMode {
	NONE = 0;
	STA = 1;
	AP = 2;
	APSTA = 3;
}

enum Ctrl_WifiBw {
	BW_Invalid = 0;
	HT20 = 1;
	HT40 = 2;
}

enum Ctrl_WifiPowerSave {
	PS_Invalid = 0;
	MIN_MODEM = 1;
	MAX_MODEM = 2;
}

/* enums for Control path */
enum Ctrl_Status {
	Connected = 0;
	Not_Connected = 1;
	No_AP_Found = 2;
	Connection_Fail = 3;
	Invalid_Argument = 4;
	Out_Of_Range = 5;
}


enum CtrlMsgType {
	MsgType_Invalid = 0;
	Req = 1;
	Resp = 2;
	Event = 3;
	MsgType_Max = 4;
}

enum CtrlMsgId {
	MsgId_Invalid = 0;

	/** Request Msgs **/
	Req_Base = 100;

	Req_GetMACAddress = 101;
	Req_SetMacAddress = 102;
	Req_GetWifiMode = 103;
	Req_SetWifiMode = 104;

	Req_GetAPScanList = 105;
	Req_GetAPConfig = 106;
	Req_ConnectAP = 107;
	Req_DisconnectAP = 108;

	Req_GetSoftAPConfig = 109;
	Req_SetSoftAPVendorSpecificIE = 110;
	Req_StartSoftAP = 111;
	Req_GetSoftAPConnectedSTAList = 112;
	Req_StopSoftAP = 113;

	Req_SetPowerSaveMode = 114;
	Req_GetPowerSaveMode = 115;

	Req_OTABegin = 116;
	Req_OTAWrite = 117;
	Req_OTAEnd = 118;

	Req_SetWifiMaxTxPower = 119;
	Req_GetWifiCurrTxPower = 120;

	Req_ConfigHeartbeat = 121;
	Req_EnableDisable = 122;
	Req_GetFwVersion = 123;
	/* Add new control path command response before Req_Max
	 * and update Req_Max */
	Req_Max = 124;

	/** Response Msgs **/
	Resp_Base = 200;

	Resp_GetMACAddress = 201;
	Resp_SetMacAddress = 202;
	Resp_GetWifiMode = 203;
	Resp_SetWifiMode = 204;

	Resp_GetAPScanList = 205;
	Resp_GetAPConfig = 206;
	Resp_ConnectAP = 207;
	Resp_DisconnectAP = 208;

	Resp_GetSoftAPConfig = 209;
	Resp_SetSoftAPVendorSpecificIE = 210;
	Resp_StartSoftAP = 211;
	Resp_GetSoftAPConnectedSTAList = 212;
	Resp_StopSoftAP = 213;

	Resp_SetPowerSaveMode = 214;
	Resp_GetPowerSaveMode = 215;

	Resp_OTABegin = 216;
	Resp_OTAWrite = 217;
	Resp_OTAEnd = 218;

	Resp_SetWifiMaxTxPower = 219;
	Resp_GetWifiCurrTxPower = 220;

	Resp_ConfigHeartbeat = 221;
	Resp_EnableDisable = 222;
	Resp_GetFwVersion = 223;
	/* Add new control path command response before Resp_Max
	 * and update Resp_Max */
	Resp_Max = 224;

	/** Event Msgs **/
	Event_Base = 300;
	Event_ESPInit = 301;
	Event_Heartbeat = 302;
	Event_StationDisconnectFromAP = 303;
	Event_StationDisconnectFromESPSoftAP = 304;
	Event_StationConnectedToAP = 305;
	Event_StationConnectedToESPSoftAP = 306;
	/* Add new control path command notification before Event_Max
	 * and update Event_Max */
	Event_Max = 307;
}

enum HostedFeature {
	Hosted_InvalidFeature = 0;
	Hosted_Wifi = 1;
	Hosted_Bluetooth = 2;

	/* Add your new features here and re-build prot using build_proto.sh */
}

message wifi_country {
	bytes          cc = 1;                      /**< country code string of 3 chars*/
	uint32         schan = 2;                   /**< start channel */
	uint32         nchan = 3;                   /**< total channel number */
	int32          max_tx_power = 4;            /**< This field is used for getting WiFi maximum transmitting power,
												  call esp_wifi_set_max_tx_power to set the maximum transmitting power. */
	int32          policy = 5;                  /**< country policy */
}

message wifi_he_ap_info {
    //uint8_t bss_color:6;                  /**< an unsigned integer whose value is the BSS Color of the BSS corresponding to the AP */
    //uint8_t partial_bss_color:1;          /**< indicate if an AID assignment rule based on the BSS color */
    //uint8_t bss_color_disabled:1;         /**< indicate if the use of BSS color is disabled */
    uint32         bitmask = 1;                 /* Manually have to parse for above bits */
    uint32         bssid_index = 2;             /**< in M-BSSID set, identifies the nontransmitted BSSID */
}

message wifi_ap_record {
	bytes          bssid = 1;                   /**< MAC address of AP 6char */
	bytes          ssid = 2;                    /**< SSID of AP 33char */
	uint32         primary = 3;                 /**< channel of AP */
	int32          second = 4;                  /**< secondary channel of AP */
	int32          rssi = 5;                    /**< signal strength of AP */
	int32          authmode = 6;                /**< authmode of AP */
	int32          pairwise_cipher = 7;         /**< pairwise cipher of AP */
	int32          group_cipher = 8;            /**< group cipher of AP */
	int32          ant = 9;                     /**< antenna used to receive beacon from AP */
	//uint32_t phy_11b:1;                       /**< bit: 0 flag to identify if 11b mode is enabled or not */
	//uint32_t phy_11g:1;                       /**< bit: 1 flag to identify if 11g mode is enabled or not */
	//uint32_t phy_11n:1;                       /**< bit: 2 flag to identify if 11n mode is enabled or not */
	//uint32_t phy_lr:1;                        /**< bit: 3 flag to identify if low rate is enabled or not */
	//uint32_t wps:1;                           /**< bit: 4 flag to identify if WPS is supported or not */
	//uint32_t ftm_responder:1;                 /**< bit: 5 flag to identify if FTM is supported in responder mode */
	//uint32_t ftm_initiator:1;                 /**< bit: 6 flag to identify if FTM is supported in initiator mode */
	//uint32_t reserved:25;                     /**< bit: 7..31 reserved */
	uint32         bitmask = 10;                /* Manually have to parse for above bits */

	wifi_country   country = 11;                /**< country information of AP */
	wifi_he_ap_info he_ap = 12;
}

message wifi_scan_threshold {
	int32          rssi = 1;                    /**< The minimum rssi to accept in the fast scan mode */
	int32          authmode = 2;                /**< The weakest authmode to accept in the fast scan mode
Note: Incase this value is not set and password is set as per WPA2 standards(password len >= 8),
it will be defaulted to WPA2 and device won't connect to deprecated WEP/WPA networks.
Please set authmode threshold as WIFI_AUTH_WEP/WIFI_AUTH_WPA_PSK to connect to WEP/WPA networks */
}

message wifi_pmf_config {
	bool           capable = 1;                 /**< Deprecated variable. Device will always connect in PMF mode if other device also advertizes PMF capability. */
	bool           required = 2;                /**< Advertizes that Protected Management Frame is required. Device will not associate to non-PMF capable devices. */
}

message wifi_ap_config {
	bytes          ssid = 1;                    /**< SSID of ESP32 soft-AP. If ssid_len field is 0, this must be a Null terminated string. Otherwise, length is set according to ssid_len. 32 char*/
	bytes          password = 2;                /**< Password of ESP32 soft-AP. 64 char*/
	uint32         ssid_len = 3;                /**< Optional length of SSID field. */
	uint32         channel = 4;                 /**< Channel of ESP32 soft-AP */
	int32          authmode = 5;                /**< Auth mode of ESP32 soft-AP. Do not support AUTH_WEP in soft-AP mode */
	uint32         ssid_hidden = 6;             /**< Broadcast SSID or not, default 0, broadcast the SSID */
	uint32         max_connection = 7;          /**< Max number of stations allowed to connect in */
	uint32         beacon_interval = 8;         /**< Beacon interval which should be multiples of 100. Unit: TU(time unit, 1 TU = 1024 us). Range: 100 ~ 60000. Default value: 100 */
	int32          pairwise_cipher = 9;         /**< pairwise cipher of SoftAP, group cipher will be derived using this.
												  cipher values are valid starting from WIFI_CIPHER_TYPE_TKIP, enum values before that will be considered as invalid and default cipher suites(TKIP+CCMP) will be used.
												  Valid cipher suites in softAP mode are WIFI_CIPHER_TYPE_TKIP, WIFI_CIPHER_TYPE_CCMP and WIFI_CIPHER_TYPE_TKIP_CCMP. */
	bool           ftm_responder = 10;          /**< Enable FTM Responder mode */
	wifi_pmf_config pmf_cfg = 11;               /**< Configuration for Protected Management Frame */
	int32         sae_pwe_h2e = 12;             /**< Configuration for SAE PWE derivation method */
}

message  wifi_sta_config {
	bytes               ssid = 1;               /**< SSID of target AP. 32char */
	bytes               password = 2;           /**< Password of target AP. 64char */
	int32               scan_method = 3;        /**< do all channel scan or fast scan */
	bool                bssid_set = 4;          /**< whether set MAC address of target AP or not. Generally, station_config.bssid_set needs to be 0,
												  and it needs to be 1 only when users need to check the MAC address of the AP.*/
	bytes               bssid = 5;              /**< MAC address of target AP 6char */
	uint32              channel = 6;            /**< channel of target AP. Set to 1~13 to scan starting from the specified channel
												  before connecting to AP. If the channel of AP is unknown, set it to 0.*/
	uint32              listen_interval = 7;    /**< Listen interval for ESP32 station to receive beacon when WIFI_PS_MAX_MODEM is set.
Units: AP beacon intervals. Defaults to 3 if set to 0. */
	int32               sort_method = 8;        /**< sort the connect AP in the list by rssi or security mode */
	wifi_scan_threshold threshold = 9;          /**< When sort_method is set, only APs which have an auth mode that is more secure
												  than the selected auth mode and a signal stronger than the minimum RSSI will be used. */
	wifi_pmf_config     pmf_cfg = 10;           /**< Configuration for Protected Management Frame. Will be advertized in RSN Capabilities in RSN IE. */
	//uint32_t rm_enabled:1;                    /**< Whether Radio Measurements are enabled for the connection */
	//uint32_t btm_enabled:1;                   /**< Whether BSS Transition Management is enabled for the connection */
	//uint32_t mbo_enabled:1;                   /**< Whether MBO is enabled for the connection */
	//uint32_t ft_enabled:1;                    /**< Whether FT is enabled for the connection */
	//uint32_t owe_enabled:1;                   /**< Whether OWE is enabled for the connection */
	//uint32_t transition_disable:1;            /**< Whether to enable transition disable feature */
	//uint32_t reserved:26;                     /**< Reserved for future feature set */
	uint32              bitmask = 11;
	int32               sae_pwe_h2e = 12;       /**< Whether SAE hash to element is enabled */
	uint32              failure_retry_cnt = 13; /**< Number of connection retries station will do before moving to next AP.
												  scan_method should be set as WIFI_ALL_CHANNEL_SCAN to use this config.
												  Note: Enabling this may cause connection time to increase incase best AP doesn't behave properly. */
    //uint32_t he_dcm_set:1;                                        /**< Whether DCM max.constellation for transmission and reception is set. */
    //uint32_t he_dcm_max_constellation_tx:2;                       /**< Indicate the max.constellation for DCM in TB PPDU the STA supported. 0: not supported. 1: BPSK, 2: QPSK, 3: 16-QAM. The default value is 3. */
    //uint32_t he_dcm_max_constellation_rx:2;                       /**< Indicate the max.constellation for DCM in both Data field and HE-SIG-B field the STA supported. 0: not supported. 1: BPSK, 2: QPSK, 3: 16-QAM. The default value is 3. */
    //uint32_t he_mcs9_enabled:1;                                   /**< Whether to support HE-MCS 0 to 9. The default value is 0. */
    //uint32_t he_su_beamformee_disabled:1;                         /**< Whether to disable support for operation as an SU beamformee. */
    //uint32_t he_trig_su_bmforming_feedback_disabled:1;            /**< Whether to disable support the transmission of SU feedback in an HE TB sounding sequence. */
    //uint32_t he_trig_mu_bmforming_partial_feedback_disabled:1;    /**< Whether to disable support the transmission of partial-bandwidth MU feedback in an HE TB sounding sequence. */
    // uint32_t he_trig_cqi_feedback_disabled:1;                     /**< Whether to disable support the transmission of CQI feedback in an HE TB sounding sequence. */
    // uint32_t he_reserved:22;                                      /**< Reserved for future feature set */
    uint32              he_bitmask = 14;
    bytes               sae_h2e_identifier = 15;                     /**< Password identifier for H2E. this needs to be null terminated string. SAE_H2E_IDENTIFIER_LEN chars */
}

message wifi_config {
	oneof u {
		wifi_ap_config    ap = 1;                 /**< configuration of AP */
		wifi_sta_config   sta = 2;                /**< configuration of STA */
	}
}

message ConnectedSTAList {
	bytes mac = 1;
	int32 rssi = 2;
}


/* Control path structures */
/** Req/Resp structure **/
message CtrlMsg_Req_GetMacAddress {
	int32 mode = 1;
}

message CtrlMsg_Resp_GetMacAddress {
	bytes mac = 1;
	int32 resp = 2;
}

message CtrlMsg_Req_GetMode {
}

message CtrlMsg_Resp_GetMode {
	int32 mode = 1;
	int32 resp = 2;
}

message CtrlMsg_Req_SetMode {
	int32 mode = 1;
}

message CtrlMsg_Resp_SetMode {
	int32 resp = 1;
}

message CtrlMsg_Req_GetStatus {
}

message CtrlMsg_Resp_GetStatus {
	int32 resp = 1;
}

message CtrlMsg_Req_SetMacAddress {
	bytes mac = 1;
	int32 mode = 2;
}

message CtrlMsg_Resp_SetMacAddress {
	int32 resp = 1;
}

message CtrlMsg_Req_GetAPConfig {
}

message CtrlMsg_Resp_GetAPConfig {
	int32 resp = 1;
	wifi_ap_record ap_records = 2;
}

message CtrlMsg_Req_ConnectAP {
	wifi_config config = 1;
}

message  CtrlMsg_Resp_ConnectAP {
	int32 resp = 1;
}

message CtrlMsg_Req_GetSoftAPConfig {
}

message CtrlMsg_Resp_GetSoftAPConfig {
	bytes ssid = 1;
	bytes pwd = 2;
	int32 chnl = 3;
	int32 sec_prot = 4;
	int32 max_conn = 5;
	bool ssid_hidden = 6;
	int32 bw = 7;
	int32 resp = 8;
	int32 band_mode = 9;
}

message CtrlMsg_Req_StartSoftAP {
	string ssid = 1;
	string pwd = 2;
	int32 chnl = 3;
	int32 sec_prot = 4;
	int32 max_conn = 5;
	bool ssid_hidden = 6;
	int32 bw = 7;
	int32 band_mode = 8;
}

message CtrlMsg_Resp_StartSoftAP {
	int32 resp = 1;
	bytes mac = 2;
	int32 band_mode = 3;
}

message CtrlMsg_Req_ScanResult {
}

message CtrlMsg_Resp_ScanResult {
	uint32 count = 1;
	repeated wifi_ap_record entries = 2;
	int32 resp = 3;
}

message CtrlMsg_Req_SoftAPConnectedSTA {
}

message CtrlMsg_Resp_SoftAPConnectedSTA {
	uint32 num = 1;
	repeated ConnectedSTAList stations = 2;
	int32 resp = 3;
}

message CtrlMsg_Req_OTABegin {
}

message CtrlMsg_Resp_OTABegin {
	int32 resp = 1;
}

message CtrlMsg_Req_OTAWrite {
	bytes ota_data = 1;
}

message CtrlMsg_Resp_OTAWrite {
	int32 resp = 1;
}

message CtrlMsg_Req_OTAEnd {
}

message CtrlMsg_Resp_OTAEnd {
	int32 resp = 1;
}

message CtrlMsg_Req_VendorIEData {
	int32 element_id = 1;
	int32 length = 2;
	bytes vendor_oui = 3;
	int32 vendor_oui_type = 4;
	bytes payload = 5;
}

message CtrlMsg_Req_SetSoftAPVendorSpecificIE {
	bool enable = 1;
	Ctrl_VendorIEType type = 2;
	Ctrl_VendorIEID idx = 3;
	CtrlMsg_Req_VendorIEData vendor_ie_data = 4;
}

message CtrlMsg_Resp_SetSoftAPVendorSpecificIE {
	int32 resp = 1;
}

message CtrlMsg_Req_SetWifiMaxTxPower {
	int32 wifi_max_tx_power = 1;
}

message CtrlMsg_Resp_SetWifiMaxTxPower {
	int32 resp = 1;
}

message CtrlMsg_Req_GetWifiCurrTxPower {
}

message CtrlMsg_Resp_GetWifiCurrTxPower {
	int32 wifi_curr_tx_power = 1;
	int32 resp = 2;
}

message CtrlMsg_Req_ConfigHeartbeat {
	bool enable = 1;
	int32 duration = 2;
}

message CtrlMsg_Resp_ConfigHeartbeat {
	int32 resp = 1;
}

message CtrlMsg_Req_EnableDisable {
	uint32 feature = 1;
	bool enable = 2;
}

message CtrlMsg_Resp_EnableDisable {
	int32 resp = 1;
}

message CtrlMsg_Req_GetFwVersion {
}

message CtrlMsg_Resp_GetFwVersion {
	int32 resp = 1;
	string name = 2;
	uint32 major1 = 3;
	uint32 major2 = 4;
	uint32 minor = 5;
	uint32 rev_patch1 = 6;
	uint32 rev_patch2 = 7;
}

/** Event structure **/
message CtrlMsg_Event_ESPInit {
	bytes init_data = 1;
}

message CtrlMsg_Event_Heartbeat {
	int32 hb_num = 1;
}

message CtrlMsg_Event_StationDisconnectFromAP {
	int32 resp = 1;
	bytes ssid = 2;
	uint32 ssid_len = 3;
	bytes bssid = 4;
	uint32 reason = 5;
	int32 rssi = 6;
}

message CtrlMsg_Event_StationConnectedToAP {
	int32 resp = 1;
	bytes ssid = 2;
	uint32 ssid_len = 3;
	bytes bssid = 4;
	uint32 channel = 5;
	int32 authmode = 6;
	int32 aid = 7;
}


message CtrlMsg_Event_StationDisconnectFromESPSoftAP {
	int32 resp = 1;
	bytes mac = 2;
	uint32 aid = 3;
	bool is_mesh_child = 4;
	uint32 reason = 5;
}

message CtrlMsg_Event_StationConnectedToESPSoftAP {
	int32 resp = 1;
	bytes mac = 2;
	uint32 aid = 3;
	bool is_mesh_child = 4;
}

message CtrlMsg {
	/* msg_type could be req, resp or Event */
	CtrlMsgType msg_type = 1;

	/* msg id */
	CtrlMsgId msg_id = 2;

	/* UID of message */
	int32 uid = 3;

	/* Request/response type: sync or async */
	uint32 req_resp_type = 4;

	/* union of all msg ids */
	oneof payload {
		/** Requests **/
		CtrlMsg_Req_GetMacAddress req_get_mac_address = 101;
		CtrlMsg_Req_SetMacAddress req_set_mac_address = 102;
		CtrlMsg_Req_GetMode req_get_wifi_mode = 103;
		CtrlMsg_Req_SetMode req_set_wifi_mode = 104;

		CtrlMsg_Req_ScanResult req_scan_ap_list = 105;
		CtrlMsg_Req_GetAPConfig req_get_ap_config = 106;
		CtrlMsg_Req_ConnectAP req_connect_ap = 107;
		CtrlMsg_Req_GetStatus req_disconnect_ap = 108;

		CtrlMsg_Req_GetSoftAPConfig req_get_softap_config = 109;
		CtrlMsg_Req_SetSoftAPVendorSpecificIE req_set_softap_vendor_specific_ie = 110;
		CtrlMsg_Req_StartSoftAP req_start_softap = 111;
		CtrlMsg_Req_SoftAPConnectedSTA req_softap_connected_stas_list = 112;
		CtrlMsg_Req_GetStatus req_stop_softap = 113;

		CtrlMsg_Req_SetMode req_set_power_save_mode = 114;
		CtrlMsg_Req_GetMode req_get_power_save_mode = 115;

		CtrlMsg_Req_OTABegin req_ota_begin = 116;
		CtrlMsg_Req_OTAWrite req_ota_write = 117;
		CtrlMsg_Req_OTAEnd req_ota_end = 118;

		CtrlMsg_Req_SetWifiMaxTxPower req_set_wifi_max_tx_power = 119;
		CtrlMsg_Req_GetWifiCurrTxPower req_get_wifi_curr_tx_power = 120;
		CtrlMsg_Req_ConfigHeartbeat req_config_heartbeat = 121;
		CtrlMsg_Req_EnableDisable req_enable_disable_feat = 122;
		CtrlMsg_Req_GetFwVersion req_get_fw_version = 123;

		/** Responses **/
		CtrlMsg_Resp_GetMacAddress resp_get_mac_address = 201;
		CtrlMsg_Resp_SetMacAddress resp_set_mac_address = 202;
		CtrlMsg_Resp_GetMode resp_get_wifi_mode = 203;
		CtrlMsg_Resp_SetMode resp_set_wifi_mode = 204;

		CtrlMsg_Resp_ScanResult resp_scan_ap_list = 205;
		CtrlMsg_Resp_GetAPConfig resp_get_ap_config = 206;
		CtrlMsg_Resp_ConnectAP resp_connect_ap = 207;
		CtrlMsg_Resp_GetStatus resp_disconnect_ap = 208;

		CtrlMsg_Resp_GetSoftAPConfig resp_get_softap_config = 209;
		CtrlMsg_Resp_SetSoftAPVendorSpecificIE resp_set_softap_vendor_specific_ie = 210;
		CtrlMsg_Resp_StartSoftAP resp_start_softap = 211;
		CtrlMsg_Resp_SoftAPConnectedSTA resp_softap_connected_stas_list = 212;
		CtrlMsg_Resp_GetStatus resp_stop_softap = 213;

		CtrlMsg_Resp_SetMode resp_set_power_save_mode = 214;
		CtrlMsg_Resp_GetMode resp_get_power_save_mode = 215;

		CtrlMsg_Resp_OTABegin resp_ota_begin = 216;
		CtrlMsg_Resp_OTAWrite resp_ota_write = 217;
		CtrlMsg_Resp_OTAEnd resp_ota_end = 218;
		CtrlMsg_Resp_SetWifiMaxTxPower resp_set_wifi_max_tx_power = 219;
		CtrlMsg_Resp_GetWifiCurrTxPower resp_get_wifi_curr_tx_power = 220;
		CtrlMsg_Resp_ConfigHeartbeat resp_config_heartbeat = 221;
		CtrlMsg_Resp_EnableDisable resp_enable_disable_feat = 222;
		CtrlMsg_Resp_GetFwVersion resp_get_fw_version = 223;

		/** Notifications **/
		CtrlMsg_Event_ESPInit event_esp_init = 301;
		CtrlMsg_Event_Heartbeat event_heartbeat = 302;
		CtrlMsg_Event_StationDisconnectFromAP event_station_disconnect_from_AP = 303;
		CtrlMsg_Event_StationDisconnectFromESPSoftAP event_station_disconnect_from_ESP_SoftAP = 304;
		CtrlMsg_Event_StationConnectedToAP event_station_connected_to_AP = 305;
		CtrlMsg_Event_StationConnectedToESPSoftAP event_station_connected_to_ESP_SoftAP = 306;
	}
}
